### PR TITLE
fix(missions): format date using dayjs

### LINKED ISSUE #348: Missions – Décalage d'une heure entre l'heure de début de mission visible dans le tableau et l'heure de début renseignée au sein du formulaire de mission.
...cela entraîne des situations fausses, où une mission apparaît comme "à venir" dans la liste alors qu'elle est déjà commencée.

### PR DESCRIPTION
**Pull request by thoomasbro**
closes #348

### CODE REVIEW

File: frontend/src/utils/getDateAsLocalizedString.tsx [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+
+export function getDateAsLocalizedStringExpanded(date: string | undefined) {
+  if (date === undefined || date.trim() === '') {
+    return undefined
+  }
+  const dayJsDate = getLocalizedDayjs(date)
+
+  return (
+    <>
+      <b>{formatDateLabel(dayJsDate.format('DD MMM'))}</b> à {dayJsDate.format('HH:mm')}
```
Comment (louptheron) [inline frontend/src/utils/getDateAsLocalizedString.tsx:18]: We don't specify it's UTC ? i.e with `15:16 (UTC)`

File: frontend/src/utils/getDateAsLocalizedString.tsx [hunk 2]
```diff
@@ -0,0 +1,34 @@
+import { getLocalizedDayjs } from '@mtes-mct/monitor-ui'
+
+export function formatDateLabel(dateLabel: string) {
```
Comment (louptheron) [inline frontend/src/utils/getDateAsLocalizedString.tsx:3]: I don't really understand what this function is doing, the day is uppercased ? Maybe we can rename the function like this ?

File: frontend/src/utils/getDateAsLocalizedString.tsx [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+
+export function getDateAsLocalizedStringCompact(date: string | undefined) {
+  if (date === undefined || date.trim() === '') {
+    return undefined
+  }
+  const dayJsDate = getLocalizedDayjs(date)
+
+  return (
+    <>
+      {formatDateLabel(dayJsDate.format('DD MMM YY'))}, {dayJsDate.format('HH')}h{dayJsDate.format('mm')}
```
Comment (louptheron) [inline frontend/src/utils/getDateAsLocalizedString.tsx:31]: Same with timezone UTC

**Review by louptheron — APPROVED** [review]
